# Generated by Django 5.2.1 on 2025-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='occupation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'occupation',
            },
        ),
    ]
