# Generated by Django 5.2.1 on 2025-05-30 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mob', models.IntegerField()),
                ('regno', models.IntegerField()),
                ('regdate', models.DateField(default=django.utils.timezone.now, max_length=20)),
                ('Docname', models.CharField(max_length=20)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.occupation_model')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
