# Generated by Django 5.2.1 on 2025-05-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_patient_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=225, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
    ]
