# Generated by Django 5.2.1 on 2025-05-30 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_complaint_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPI_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset', models.DateField(max_length=20)),
                ('current_date', models.DateField(default=django.utils.timezone.now, max_length=20)),
                ('painscore', models.IntegerField()),
                ('Duration', models.CharField(max_length=100)),
                ('POS', models.CharField(max_length=200)),
                ('Aggr', models.CharField(max_length=200)),
                ('Relf', models.CharField(max_length=200)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'HPI',
            },
        ),
    ]
