# Generated by Django 5.2.1 on 2025-05-31 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_hpi_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMHM_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmc', models.CharField(max_length=225, null=True)),
                ('surgeries', models.CharField(max_length=225)),
                ('Injuries', models.CharField(max_length=225)),
                ('medications', models.CharField(max_length=225)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'PMHM',
            },
        ),
    ]
