# Generated by Django 5.2.1 on 2025-05-31 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_pmhm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHistory_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle', models.CharField(max_length=225)),
                ('activitylevels', models.CharField(max_length=225)),
                ('habits', models.CharField(max_length=225)),
                ('healthissues', models.CharField(max_length=225)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'SH',
            },
        ),
    ]
