# Generated by Django 5.2.1 on 2025-05-31 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_socialhistory_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='objectiveassessment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postureandmovement', models.TextField(max_length=225)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'ObjAss',
            },
        ),
    ]
