# Generated by Django 5.2.1 on 2025-05-31 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_romtype_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='cervicalspinemotion_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motionname', models.CharField(max_length=30)),
                ('typename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.romtype_model')),
            ],
            options={
                'db_table': 'CS',
            },
        ),
    ]
