# Generated by Django 5.2.1 on 2025-05-31 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_cervicalspinemotion_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROM_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.IntegerField()),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('motionname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.cervicalspinemotion_model')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
                ('typename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.romtype_model')),
            ],
            options={
                'db_table': 'ROM',
            },
        ),
    ]
