# Generated by Django 5.2.1 on 2025-05-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_rom_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMT_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'MMT',
            },
        ),
    ]
