# Generated by Django 5.2.1 on 2025-06-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_spte_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PALPATION_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderness', models.CharField(max_length=100)),
                ('swelling', models.CharField(max_length=100)),
                ('muscletone', models.CharField(max_length=100)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'PALP',
            },
        ),
    ]
