# Generated by Django 5.2.1 on 2025-06-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_palpation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEUROASS_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflexes', models.CharField(max_length=100)),
                ('sensation', models.CharField(max_length=100)),
                ('nervefunction', models.CharField(max_length=100)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'NEURO',
            },
        ),
    ]
