# Generated by Django 5.2.1 on 2025-06-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_neuroass_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUNCTIONLIM_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentofcondition', models.CharField(max_length=200)),
                ('activitiesofdailyiving', models.CharField(max_length=200)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'FUNLIM',
            },
        ),
    ]
