# Generated by Django 5.2.1 on 2025-06-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_functionlim_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIAGNOS_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xrays', models.CharField(max_length=200)),
                ('MRI', models.CharField(max_length=200)),
                ('CT', models.CharField(max_length=200)),
                ('lab', models.CharField(max_length=200)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'DIAGNOS',
            },
        ),
    ]
