# Generated by Django 5.2.1 on 2025-06-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_impression_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHYSIOGOALS_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorttermgoals', models.CharField(max_length=225)),
                ('longtermgoals', models.CharField(max_length=225)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'PHYSIO',
            },
        ),
    ]
