# Generated by Django 5.2.1 on 2025-06-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_planofcare_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PATIENTEDUCATION_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanationofcondition', models.CharField(max_length=225)),
                ('prognosis', models.CharField(max_length=225)),
                ('selfmanagement', models.CharField(max_length=225)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'PATIENTEDUCATION',
            },
        ),
    ]
