# Generated by Django 5.2.1 on 2025-06-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_followupplan_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FOLLOWUPPLAN_model',
        ),
    ]
