# Generated by Django 5.2.1 on 2025-06-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_delete_followupplan_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOLLOWUPPLAN_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencyofvisits', models.CharField(max_length=225)),
                ('reassessment', models.CharField(max_length=225)),
                ('modifications', models.CharField(max_length=225)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
            ],
            options={
                'db_table': 'FOLLOWUPPLAN',
            },
        ),
    ]
