# Generated by Django 5.2.1 on 2025-06-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_followupplan_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FALLRISKSCREENING_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteriatype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'FALLRISKSCREENING',
            },
        ),
        migrations.AlterModelTable(
            name='followupplan_model',
            table=None,
        ),
    ]
