# Generated by Django 5.2.1 on 2025-06-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_fallriskscreening_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRITERIAsection_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionname', models.CharField(max_length=20)),
                ('criteriatype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.fallriskscreening_model')),
            ],
            options={
                'db_table': 'CRITERIA',
            },
        ),
    ]
