# Generated by Django 5.2.1 on 2025-06-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_criteriasection_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('Date', models.DateField(max_length=20, null=True)),
                ('criteriatype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.fallriskscreening_model')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
                ('sectionname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.criteriasection_model')),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
    ]
