# Generated by Django 5.2.1 on 2025-06-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_totalscore_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TS1_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=20, null=True)),
                ('facility', models.CharField(max_length=225, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_model')),
                ('range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.totalscore_model')),
            ],
            options={
                'db_table': 'TS1',
            },
        ),
    ]
