# Generated by Django 5.2.1 on 2025-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_ts1_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apppointment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('Department', models.CharField(max_length=30)),
                ('Message', models.TextField(max_length=220, null=True)),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
